### ISSUE TITLE
Land Acknowledgement Slice (popup when polygon clicked)

### ISSUE THREAD

**Issue by mccrayjr** [the-bat-signal/rooted#2]
- [x] popup when click on map (deck.gl functionality)
- [x] pop up includes land acknowledgement statement, overall info and link to SingleLanguageView
- [x] popup needs to reopen after being closed
- [x] popup needs proper sizing/styling
- [x] link to SingleLanguageView works

**Comment by kendimoraski** [comment]
3/24/21
- The majority of the skeleton of information is there, using the hardcoded Dakota sample. Right now position is set to absolute, but it does not automatically show the entirety of the popup box. Any other position option is undesirable here because it moves it around the screen and off the map onto the page underneath. 
- To do: fix styling, do some resizing and colors, implement links, find a way to make this work dynamically for media queries and moving around the map
- try to get some technology that actually builds Popups, like Reactjs-Popup, to work given that we are using onClick on a Polygon to trigger the popup box to begin with

**Comment by kendimoraski** [comment]
Need to edit this code so that it calls **all** languages, territories, and vocab
